kind: Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaos-monkey
  namespace: default
  labels:
    symbiont: "true"
    component: frontend
    name: chaos-monkey
    symbiont.io/nodectld-managed: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-monkey
    spec:
      imagePullSecrets:
        - name: docker-registry-key
      containers:
        - name: chaos-monkey
          image: "us.gcr.io/development-148212/chaos_monkey:v.0.0.1"
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.1"
          env:
            - name: "CHAOS_MONKEY_POD_NAME"
              value: "aurora-onramp"
            - name: "CHAOS_MONKEY_KILL_FREQUENCY_UPPER_LIMIT"
              value: "36000"
